# Generated by Django 2.0.7 on 2019-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190128_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='avatars'),
        ),
    ]
