# Generated by Django 2.0.7 on 2019-01-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default='unknown', max_length=50),
        ),
    ]
